#!/usr/bin/perl
use strict;
use warnings;

my $netstat = `ifconfig -s`;

my @devs = qw(ppp eth wlan);

for my $dev(@devs){
  my $device = `ifdev $dev`;
  chomp $device;
  if($? == 0 and $netstat =~ /^$device /m){
    print "$dev\n";
  }
}

