#!/usr/bin/perl
use strict;
use warnings;

my $USE_NETWORK_MANAGER = 0;

my $DEV = '/dev/ttyACM0';
my $CONFIG = "$ENV{HOME}/wvdial.conf";

my $arg = shift;
$arg = 'toggle' if not defined $arg;
if(($arg ne 'on' and $arg ne 'off' and $arg ne 'toggle') or @ARGV > 0){
  die "Usage: $0 [on|off|toggle]  {toggle is default}\n";
}


if($arg ne 'off' and not -e $DEV){
  print STDERR "Device $DEV not found:\nrunning $0 off instead of $0 $arg\n";
  $arg = 'off';
}

if($arg eq 'toggle'){
  system "pidof pppd wvdial";
  my $isUp = $? == 0;
  $arg = $isUp ? 'off' : 'on';
}

my $peerFile = '/etc/ppp/peers/wvdial';

if($arg eq 'on'){
  print "tethering ON and wifi off\n";
  my @lines = `cat $peerFile`;
  for my $line(@lines){
    $line =~ s/^usepeerdns\n?$//;
  }
  open FH, "> $peerFile" or die "Could not write to $peerFile\n$!";
  print FH @lines;
  close FH;
  system 'killall', '-9', 'pppd', 'wvdial';
  system "initctl stop network-manager" if $USE_NETWORK_MANAGER;
  system "resolvChooser default";
  system "wconnect -d";
  system 'wvdial', '-C', $CONFIG;
  system "wauto --action ppp-connect";
}elsif($arg eq 'off'){
  print "tethering OFF and wifi on\n";
  system "initctl start network-manager" if $USE_NETWORK_MANAGER;
  system 'killall', '-9', 'pppd', 'wvdial';
  system "wauto --action ppp-disconnect";
}
