#!/usr/bin/perl
use strict;
use warnings;

my $DEV = '/dev/ttyACM0';
my $CONFIG = "$ENV{HOME}/wvdial.conf";

my $arg = shift() || 'toggle';
if(@ARGV > 0 or $arg !~ /^(on|off|toggle)$/){
  die "Usage: $0 [on|off|toggle]  {toggle is default}\n";
}

if($arg eq 'toggle'){
  system "pidof pppd wvdial";
  my $isUp = $? == 0;
  $arg = $isUp ? 'off' : 'on';
}

if($arg ne 'off' and not -e $DEV){
  print STDERR "Device $DEV not found: untethering instead\n";
  $arg = 'off';
}

if($arg eq 'on'){
  print "tethering...\n";
  system 'killall', '-9', 'pppd', 'wvdial';
  system "wconnect -d";
  system 'wvdial', '-C', $CONFIG;
  system "resolv";
}elsif($arg eq 'off'){
  print "untethering...\n";
  system 'killall', '-9', 'pppd', 'wvdial';
}
