#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long qw(GetOptionsFromArray);

my $usage = "Usage: $0 [--wired] [-p|--ping]\n";

sub main(@){
  my $wired;
  my $pingTest;
  GetOptionsFromArray(\@_,
    "wired" => \$wired,
    "ping|p" => \$pingTest,
  );

  die $usage if @_ > 0;
  if(defined $pingTest){
    my $test = `execPing --attempts=1`;
    if($test =~ /^ok:/){
      print "ping test succeeded, skipping wauto\n";
      exit 0;
    }
  }
  my $wautoPidfile = '/tmp/wauto-pidfile';
  if(-e $wautoPidfile){
    system "kill -9 `cat $wautoPidfile` >/dev/null 2>/dev/null";
  }
  system "echo $$ > $wautoPidfile";

  if($wired){
    system "wired";
    exit if $? == 0;
  }

  my $ssid = `wguessid`;
  system "wconnect", "-d";
  if($? == 0){
    chomp $ssid;
    print "SSID: $ssid\n";
    system "wconnect", $ssid;
  }else{
    die "No suitable ssid found\n";
  }
}

&main(@ARGV);
