#!/usr/bin/perl
use strict;
use warnings;

my $wpaConf = '/tmp/wpa_supplicant.conf';
$ENV{PATH}='/bin:/usr/bin:/usr/local/bin:/sbin:/usr/local/sbin';
my $home = $ENV{HOME};
$home =~ /^([a-zA-Z0-9_\-\/]+)$/;
$home = $1;
my $wifiConf = "$home/wifi.conf";

my $dev = `ifdev wlan`;
$dev =~ /(wlan\d+)/;
$dev = $1;

my $justDisconnect = 0;

my ($list, $ssid, $encMode, $key);
if(@ARGV == 1 and $ARGV[0] eq '--list'){
  $list = 1;
}elsif(@ARGV == 1 and $ARGV[0] eq '-d'){
  $justDisconnect = 1;
}else{
  $list = 0;
  $ssid = shift;
  $encMode = shift;
  $key = shift;
}

my @networks;
if(-e $wifiConf){
  my $unsafeCode = `cat $wifiConf`;
  $unsafeCode =~ /(.*)/s;
  $unsafeCode = $1;
  use Safe;
  @networks = new Safe() -> reval($unsafeCode);
  no Safe;
}

if($list){
  for my $net(@networks){
    print "$$net[0]\n";
  }
  exit 0;
}

if(defined $ssid and (not defined $encMode or not defined $key)){
  for my $network(@networks){
    if($ssid eq $$network[0]){
      print "preconfigured network\n";
      $encMode = $$network[1];
      $key = $$network[2];
      last;
    }
  }
}
if(defined $ssid and (not defined $encMode or not defined $key)){
  for my $network(@networks){
    if(lc $ssid eq lc $$network[0]){
      $ssid = $$network[0];
      print "preconfigured network, case changed to $ssid\n";
      $encMode = $$network[1];
      $key = $$network[2];
      last;
    }
  }
}

if(not defined $encMode or not defined $key){
  $encMode = 'NONE';
  $key = '';
}


my $amRoot = `whoami` eq "root\n";
sub runsudo(@){
  @_ = ('sudo', @_) if not $amRoot;
  print "exec: " . join(' ', @_) . "\n";
  system @_;
}

runsudo "killall", "wpa_supplicant", "dhclient";
exit 0 if $justDisconnect;

if(not defined $ssid or $encMode !~ /^(WPA|WPA2|WEP|NONE)$/){
  die "Usage:
    $0 <SSID> [WPA|WPA2|WEP|NONE] [key]
    $0 --list
  ";
}


if($encMode eq 'WPA' or $encMode eq 'WPA2'){
  my $conf = "network={
       ssid=\"$ssid\"
       psk=\"$key\"
  }\n";
  open FH, "> $wpaConf";
  print FH $conf;
  close FH;
  runsudo "ifconfig", $dev, "up";
  runsudo "wpa_supplicant", "-B", "-Dwext", "-i$dev", "-c$wpaConf";
  runsudo "sleep", "1";
}elsif($encMode eq 'WEP'){
  runsudo "ifconfig", $dev, "up";
  runsudo "iwconfig", $dev, "essid", $ssid, "key", $key, "channel", "auto";
}elsif($encMode eq 'NONE'){
  runsudo "ifconfig", $dev, "up";
  runsudo "iwconfig", $dev, "essid", $ssid, "channel", "auto";
}

runsudo "resolvchooser", "default";
runsudo "dhclient", "$dev";
