#!/usr/bin/perl
use strict;
use warnings;

my $winfoExec = 'winfo';

sub main(@){
  die "Usage: $0\n" if @_ > 0;
  my %auto = map {/^(\d+):(.*)$/; $2 => $1} `$winfoExec --exact --list-auto`;
  my $guess;
  my $autoPriority;
  for my $ssid(`wscan 3 --retry --ssids`){
    chomp $ssid;
    my $p = $auto{$ssid};
    if(defined $p and (not defined $autoPriority or $p < $autoPriority)){
      $guess = $ssid;
      $autoPriority = $p;
    }
  }
  if(defined $guess){
    print "$guess\n";
  }else{
    die "error: no auto networks available\n";
  }
}

&main(@ARGV);
