#!/usr/bin/perl
use strict;
use warnings;

if(`whoami` ne "root\n"){
  print STDERR "rerunning as root...\n";
  exec "sudo", "$0", @ARGV;
}

my $arg = shift;
$arg = 'on' if not defined $arg;

die "$0 [on|off] {default: on}" if @ARGV > 0 or $arg !~ /^(on|off|toggle)$/;

my $dev = `ifdev eth`;
chomp $dev;
if($dev !~ /^eth/){
  die "no suitable device {i.e. named eth#} found\n";
}

sub run(@){
  print "@_\n";
  system @_;
}

print "\ndisconnecting wired\n";
run "ifconfig", $dev, "down";
run "pkill", "-f", "^dhclient $dev\$";

if($arg eq 'on'){
  print "\nconnecting wired\n";
  run "ifconfig", $dev, "up";
  my $carrier = `cat "/sys/class/net/$dev/carrier"`;
  chomp $carrier;
  if($carrier eq "1"){
    run "dhclient $dev";
  }else{
    print STDERR "\nerror: cable is disconnected\n";
    exit 1;
  }
}
