#!/usr/bin/perl
use strict;
use warnings;

my @devs = qw(ppp eth wlan);
my $wconnect = 'wconnect';
my $wauto = 'wauto';
my $tethering = 'tethering';
my $none = 'none';

my $okStatuses = join ',', ($wauto, $tethering, $none, @devs);
my $usage = "Usage: $0  print one of [$okStatuses]\n";

sub getDev();
sub isWconnect();
sub isWauto();
sub isTethering();


sub main(@){
  die $usage if @_ > 0;
  my $status = getDev();
  $status = $wconnect if not defined $status and isWconnect();
  $status = $wauto if not defined $status and isWauto();
  $status = $tethering if not defined $status and isTethering();
  $status = $none if not defined $status;
  print "$status\n";
}

sub getDev(){
  my @devs = qw(ppp eth wlan);
  my $netstat = `ifconfig -s`;

  for my $dev(@devs){
    my $device = `ifdev $dev 2>/dev/null`;
    chomp $device;
    if($? == 0 and $netstat =~ /^$device /m){
      if($dev eq 'wlan'){
        my $iwconfig = `iwconfig $device`;
        if($iwconfig =~ /ESSID:off\/any\s*$/m){
          next;
        }
      }
      if(`ifconfig $device` =~ /inet addr/){
        return $dev;
      }
    }
  }
  return undef;
}

sub isWconnect(){
  system "pgrep wconnect > /dev/null 2>/dev/null";
  return $? == 0;
}

sub isWauto(){
  system "pgrep wauto > /dev/null 2>/dev/null";
  return $? == 0;
}

sub isTethering(){
  system "pidof pppd wvdial > /dev/null 2>/dev/null";
  return $? == 0;
}

&main(@ARGV);
