#!/usr/bin/perl
use strict;
use warnings;

my $netstat = `ifconfig -s`;
my $lastActionFile = '/tmp/net_action';

my @devs = qw(ppp eth wlan);

for my $dev(@devs){
  my $device = `ifdev $dev`;
  chomp $device;
  if($? == 0 and $netstat =~ /^$device /m){
    if($dev eq 'wlan'){
      my $iwconfig = `iwconfig $device`;
      if($iwconfig =~ /ESSID:off\/any\s*$/m){
        next;
      }
    }
    print "$dev\n";
    exit 0;
  }
}

print "none\n";
exit 0;
